### PR TITLE
Fix ESLint errors related to SDK and AST generation for TS and JS

### PR DESCRIPTION
**Pull request by costinsin**
## Type of change

-   [x] 🧑‍💻 Improvement

## Description
Changed the TS and JS SDK/AST generation to use proper types and also throw errors for unsupported language features.

## Checklist

-   [x] My code follows the contributor guidelines of this project;
-   [x] New and existing unit tests pass locally with my changes;

### CODE REVIEW

**Comment by costinsin** [comment]
Current dependencies on/for this PR:
* dev
  * **PR #604** <a href="https://app.graphite.dev/github/pr/Genez-io/genezio/604?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/Genez-io/genezio/604?utm_source=stack-comment).

**Comment by andreia-oca** [comment]
I took a look at this PR, looks good. As discusses offline, please fix the object default value for optionals in JavaScript.

I'll take a look again at the PR after that is solved.

**Comment by costinsin** [comment]
@andreia-oca I have solved the discussed ObjectExpression problem. It now pastes the ObjectExpression literal from the code as default value.

**Review by andreia-oca — APPROVED** [review]
LGTM 🥳

**Pull request merged**
