### PR TITLE
Throw error if frontend publish folder is missing

### PR DESCRIPTION
**Pull request by vladiulianbogdan**
# Pull Request Template

## Type of change

-   [ ] 🍕 New feature
-   [x] 🐛 Bug Fix
-   [ ] 🔥 Breaking change
-   [ ] 🧑‍💻 Improvement
-   [ ] 📝 Documentation Update

## Description

Throw error if frontend `publish` folder is missing instead of just returning a warning.

## Checklist

-   [x] My code follows the contributor guidelines of this project;
-   [ ] I have updated the documentation;
-   [ ] I have added tests;
-   [x] New and existing unit tests pass locally with my changes;

### CODE REVIEW

**Comment by costinsin** [comment]
I think there are situations where you want to generate a SDK, but you don't want to publish anything. This is the case when you leave publish not defined.

**Comment by costinsin** [comment]
Also this is not the right change if you intend to enforce publish. You need to change the `zod` definition.

**Review by radu1122 — APPROVED** [review]

**Comment by vladiulianbogdan** [comment]
> I think there are situations where you want to generate a SDK, but you don't want to publish any frontend. This is the case when you leave publish not defined.

Could you use this in that scenario https://genezio.com/docs/cli-tool/cli-commands/generatesdk/? 

The thing is that it has some weird side effects the fact that you have a frontend without `publish`. For example if you would import [this](https://github.com/paulacionca/nodejs-serverless-function-express) project via the Github Integration, it will seem as if everything worked fine, but it is actually a misconfiguration.

**Review by costinsin — APPROVED** [review]
LGTM

**Pull request merged**
